name: CI
on:
  push:
    branches:
      - th20tr-mainline

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild environment
      uses: microsoft/setup-msbuild@v2
      with:
          msbuild-architecture: x86
    - name: Build thprac
      run: msbuild thprac.sln -t:restore,build -p:RestorePackagesConfig=true,Configuration=Release
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: thprac
        path: |
            Release/thprac.exe
            Release/thprac.pdb
